import {spawn,spawnSync} from 'node:child_process';
import {mkdtempSync,rmSync,symlinkSync,readFileSync,readdirSync,existsSync} from 'node:fs';
import {homedir,tmpdir} from 'node:os';
import {dirname,join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {parseTask} from '../scripts/ai-task.mjs';
const ROOT=dirname(dirname(fileURLToPath(import.meta.url)));
const STORE=mkdtempSync(join(tmpdir(),'browse-ai-task-'));
symlinkSync(join(homedir(),'.browse/camoufox-pw'),join(STORE,'camoufox-pw'));
const ENV={...process.env,BROWSE_HOME:STORE,BROWSE_OUT:join(STORE,'out'),BROWSE_PW_BASE:join(homedir(),'.browse/package.json'),BROWSE_SESSION:'task-test',BROWSE_ENGINE:process.env.BROWSE_ENGINE||'chromium',BROWSE_REMOTE:'',BROWSE_PROFILE:'',BROWSE_VIDEO:'0',BROWSE_HEADFUL:'0',BROWSE_CURSOR:'0',BROWSE_KEYLOG:'0',TYPESAFE_API_KEY:'fake-task-key',TYPESAFE_ENV_FILE:join(STORE,'absent')};
const b=(...args)=>{const r=spawnSync(process.execPath,[join(ROOT,'browse.mjs'),...args],{env:ENV,cwd:STORE,encoding:'utf8',timeout:30000});return{code:r.status,out:r.stdout||'',err:r.stderr||''}};
let checks=0,failed=0;
const check=(name,ok,detail='')=>{checks++;if(!ok)failed++;console.log(`${ok?'ok':'FAIL'} ${name}${ok?'':'\n'+detail}`)};
const fixture=spawn(process.execPath,[join(ROOT,'test/ai-task-fixture.mjs')],{stdio:['ignore','pipe','inherit']});
const port=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('fixture timeout')),10000);fixture.stdout.on('data',d=>{const m=/PORT (\d+)/.exec(String(d));if(m){clearTimeout(timer);resolve(+m[1])}})});
const base=`http://127.0.0.1:${port}`;ENV.TYPESAFE_API_URL=base+'/api';
const mode=m=>fetch(base+'/mode/'+m);
const goal='Open the catalog, open Desk lamp details, choose Express delivery, enter the supplied email, then submit the request.';
const task=(...args)=>b('ai','task',goal,'--value','email=buyer@example.invalid',...args);
try{
  const p=parseTask(['task','Search for "Typesafe" and open the result']);check('quoted goal supplies literal input',p.values[0].value==='Typesafe');
  for(const args of [['task'],['task','goal','--max-steps','0'],['task','goal','--task-timeout','0'],['task','goal','--value','bad'],['task','goal','--dry-run'],['task','goal','--until']]){const r=b('ai',...args);check(`invalid args fail before launching: ${args.join(' ')}`,r.code===1&&!existsSync(ENV.BROWSE_OUT),r.err)}
  let r=b('open',base);check('fixture opens',r.code===0,r.err);
  r=task();check('one command completes five-step workflow',r.code===0&&/completed; actions=5, queries=6/.test(r.out),r.out+r.err);
  check('actual final page confirms result',b('text','#confirmed').out.includes('Request confirmed'));
  check('submit runs exactly once',b('eval','document.documentElement.dataset.sends').out.trim()==='1');
  check('all five actions have screenshots',readdirSync(join(ENV.BROWSE_OUT,'shots')).filter(n=>n.includes('ai-task')).length===5);
  const calls=await(await fetch(base+'/calls')).json();
  check('each decision reads fresh controls after navigation',calls.length===6&&calls[0].state.page.text.includes('Store')&&calls.at(-1).state.page.text.includes('Request confirmed'));
  check('named fill value stays out of model requests',!JSON.stringify(calls).includes('buyer@example.invalid')&&!JSON.stringify(calls).includes('old@example.invalid'));
  check('history tracks actions and value references',calls[4].state.history.some(h=>h.action==='fill'&&h.value==='v0'));
  check('history retains observed views after navigating away',calls.at(-1).state.history.some(h=>h.observedAfter?.headings.includes('Catalog')));
  check('history retains confirmed form facts after submission removes the form',calls.at(-1).state.history.some(h=>h.observedAfter?.form?.some(c=>c.filledWith?.includes('v0'))));
  b('reload');await mode('early-done');r=task();
  check('premature completion is reconsidered and unfinished work proceeds',r.code===0&&/Rejected completion/.test(r.out)&&/completed; actions=5, queries=7/.test(r.out),r.out+r.err);
  b('reload');await mode('ok');r=task('--until','#confirmed');check('deterministic completion avoids final model call',r.code===0&&/completed \(--until visible\); actions=5, queries=5/.test(r.out),r.out+r.err);
  b('reload');await mode('ok');r=task('--max-steps','1');check('step limit preserves completed action and stops',r.code===1&&/step limit reached/.test(r.err)&&b('eval','JSON.parse(document.documentElement.dataset.events)').out.includes('catalog')&&!b('eval','JSON.parse(document.documentElement.dataset.events)').out.includes('lamp'),r.err);
  check('partial steps are persisted before failure',readFileSync(join(ENV.BROWSE_OUT,'transcript.md'),'utf8').includes('ai task\n'));
  for(const m of ['blocked','low','invalid','false-done','error']){b('reload');await mode(m);r=task();check(`${m} stops without clicking`,r.code===1&&b('eval','JSON.parse(document.documentElement.dataset.events).length').out.trim()==='0',r.out+r.err)}
  b('open','data:text/html,<h1>Complete</h1><input value=private-data-url-value>');await mode('done');r=task();
  const dataCalls=await(await fetch(base+'/calls')).json();check('data URL source and input values stay out of requests',r.code===0&&!JSON.stringify(dataCalls).includes('private-data-url-value')&&dataCalls[0].state.page.url==='data:',r.err);
  b('open',base);await mode('done');r=task('--until','#confirmed');check('model cannot bypass completion selector',r.code===1&&/selector is not visible/.test(r.err),r.err);
  b('reload');b('eval',"document.querySelector('#catalog').onclick=()=>{};'ready'");await mode('loop');r=task();check('no-op cycle stops before repeating click',r.code===1&&/stalled/.test(r.err)&&(r.err.match(/\d+\. Click \"Open catalog\"/g)||[]).length===1,r.err);
  b('reload');await mode('wait');r=task();check('wait loop is bounded',r.code===1&&/stalled/.test(r.err)&&/actions=6/.test(r.err),r.err);
  b('reload');await mode('slow');r=task('--task-timeout','150');check('total deadline cancels inference',r.code===1&&/cancelled|budget/.test(r.err)&&b('eval','JSON.parse(document.documentElement.dataset.events).length').out.trim()==='0',r.err);
  b('reload');await mode('slow');
  b('eval', "setTimeout(()=>{const el=document.createElement('div');el.id='arrived';el.textContent='Ready';document.body.append(el)},400);'scheduled'");
  r=task('--until','#arrived');
  check('completion during inference prevents an obsolete action',r.code===0&&/actions=0, queries=1/.test(r.out)&&b('eval','document.documentElement.dataset.events').out.trim()==='[]',r.out+r.err);
  b('reload');await mode('slow');
  const run=JSON.parse(readFileSync(join(STORE,'run/task-test.json'),'utf8'));
  const endpoint=`http://127.0.0.1:${run.port}`;
  const controller=new AbortController();
  const active=fetch(endpoint,{method:'POST',signal:controller.signal,body:JSON.stringify({cmd:'ai',args:['task',goal,'--value','email=buyer@example.invalid'],ai:{key:'fake-task-key',endpoint:base+'/api'}})}).catch(()=>null);
  await new Promise(r=>setTimeout(r,200));
  const concurrent=await(await fetch(endpoint,{method:'POST',body:JSON.stringify({cmd:'click',args:['#catalog']})})).json();
  check('concurrent browser command is rejected during task',!concurrent.ok&&/task is running/.test(concurrent.error));
  controller.abort();await active;await new Promise(r=>setTimeout(r,100));
  r=b('eval','JSON.parse(document.documentElement.dataset.events).length');check('disconnected caller cancels task and unlocks session',r.code===0&&r.out.trim()==='0',r.out+r.err);
  await mode('ok');b('reload');
  const waiting=fetch(endpoint,{method:'POST',body:JSON.stringify({cmd:'wait',args:['400']})});
  await new Promise(r=>setTimeout(r,40));
  const occupied=await(await fetch(endpoint,{method:'POST',body:JSON.stringify({cmd:'ai',args:['task',goal],ai:{key:'fake-task-key',endpoint:base+'/api'}})})).json();
  check('task cannot overlap an earlier browser command',!occupied.ok&&/another browser command/.test(occupied.error));await waiting;
  b('click','#catalog');b('click','#lamp');await mode('slow');
  b('eval',"setTimeout(()=>document.querySelector('#delivery').options[1].label='Unexpected option',500);'scheduled'");
  r=task();check('changed native option is rejected before selection',r.code===1&&/blocked|target changed/.test(r.err)&&b('eval',"document.querySelector('#delivery').selectedIndex").out.trim()==='0',r.err);
  b('reload');b('click','#catalog');b('click','#lamp');b('selectOption','#delivery','Express');await mode('bad-value');
  r=task();check('invalid supplied value prevents filling',r.code===1&&/invalid decision/.test(r.err)&&b('eval',"document.querySelector('#email').value").out.trim()==='old@example.invalid',r.err);
  await mode('ok');b('reload');r=task();check('session remains usable after cancellation',r.code===0,r.out+r.err);
  await mode('loop');
  r=b('eval', `document.body.innerHTML='<input aria-label="Departure"><div id="picker" role="dialog" aria-label="Choose dates" tabindex="-1" hidden><div role="gridcell" tabindex="0"><button aria-labelledby="date-label"><span id="date-label" aria-label="Monday, October 12, 2026">12</span></button></div></div>'; document.querySelector('input').onclick=()=>document.querySelector('#picker').hidden=false;document.querySelector('button').onclick=()=>{document.body.dataset.picked='1';document.querySelector('button').id='picked'}; 'ready'`);
  check('picker fixture is ready',r.code===0,r.err);
  r=b('ai','task','Open the Departure calendar','--until','#picker');
  check('editable input can be clicked to open a picker without a fill value',r.code===0&&/actions=1/.test(r.out),r.out+r.err);
  await mode('loop');
  r=b('ai','task','Choose October 12','--scope','#picker','--until','#picked');
  check('calendar task clicks the day button',r.code===0&&b('eval','document.body.dataset.picked').out.trim()==='1',r.out+r.err);
  const calendarCalls=await(await fetch(base+'/calls')).json();
  const calendarControls=calendarCalls[0]?.state.page.controls||[];
  check('referenced accessible date label is preserved',calendarControls.some(c=>c.name==='Monday, October 12, 2026'));
  check('container and nested gridcell do not become duplicate actions',calendarControls.length===1&&calendarControls[0].tag==='button',JSON.stringify(calendarControls));
  b('eval', "document.querySelector('#picked').id='';document.querySelector('button').removeAttribute('aria-labelledby');delete document.body.dataset.picked; 'ready'");
  await mode('loop');r=b('ai','task','Choose October 12','--scope','#picker','--until','#picked');
  const childCalls=await(await fetch(base+'/calls')).json();
  check('custom day button inherits the child date label',r.code===0&&childCalls[0].state.page.controls[0].name.includes('Monday, October 12, 2026'),r.out+r.err);
  b('reload');await mode('verify');r=task('--until','#lamp');
  check('uncertain choice can advance after independent verification',r.code===0&&/actions=1, queries=2/.test(r.out)&&/independently verified/.test(r.out),r.out+r.err);
  b('reload');await mode('deny-verification');r=task();
  check('rejected independent verification never acts',r.code===1&&/actions=0, queries=3/.test(r.err)&&b('eval','document.documentElement.dataset.events').out.trim()==='[]',r.err);
  b('reload');await mode('retry-choice');r=task('--until','#lamp');
  check('rejected proposal is reconsidered without caller intervention',r.code===0&&/Rejected decision/.test(r.out)&&/actions=1, queries=3/.test(r.out),r.out+r.err);
  await mode('loop');
  r=b('eval', `document.body.innerHTML='<button id="background">Wrong background action</button><div role="dialog" aria-label="Pick a date" style="position:fixed;left:100px;top:100px;width:300px;height:200px"><div role="tabpanel" style="position:relative;width:300px;height:200px"><div role="button" aria-label="October 12" style="position:absolute;left:80px;top:60px;width:80px;height:40px">12</div><canvas role="grid" width="300" height="200" style="position:absolute;inset:0"></canvas></div></div>';document.querySelector('#background').onclick=()=>document.body.dataset.wrong='1';document.querySelector('canvas').onclick=e=>{if(e.offsetX>=80&&e.offsetX<=160&&e.offsetY>=60&&e.offsetY<=100){document.body.innerHTML='<h1 id="canvas-done">Date selected</h1>'}};'ready'`);
  check('canvas fixture is ready',r.code===0,r.err);
  b('eval', "const ctx=document.querySelector('canvas').getContext('2d');ctx.fillStyle='blue';ctx.fillRect(80,60,80,40);'painted'");
  r=b('ai','task','Choose October 12','--until','#canvas-done');
  check('one goal automatically scopes modal and clicks canvas-backed date',r.code===0&&/actions=1/.test(r.out),r.out+r.err);
  const canvasCalls=await(await fetch(base+'/calls')).json();
  check('modal background is excluded without a supplied scope',canvasCalls[0].state.page.region==='Pick a date'&&!canvasCalls[0].state.page.controls.some(c=>c.name==='Wrong background action'));
  check('painted canvas metadata accompanies its accessible cells',canvasCalls[0].state.page.graphics.some(g=>g.painted===true));
  await mode('loop');
  b('eval', `document.body.innerHTML='<div role="dialog"><button style="position:absolute;left:100px;top:100px;width:100px;height:50px">Blocked</button><div style="position:absolute;left:100px;top:100px;width:100px;height:50px;z-index:5">Cover</div></div>';document.querySelector('button').onclick=()=>document.body.dataset.unsafe='1';'ready'`);
  r=b('ai','task','Click Blocked','--timeout','400');
  check('ordinary overlay is never force clicked',r.code===1&&!b('eval','document.body.dataset.unsafe').out.includes('1'),r.out+r.err);
  await mode('done');
  b('eval', `document.body.innerHTML='<h1>Review</h1><label>Travel date<input value="Mon, Oct 12"></label><label>Private note<input value="unrelated-hidden-value"></label>'; 'ready'`);
  r=b('ai','task','Review the date October 12, 2026');
  const dateCalls=await(await fetch(base+'/calls')).json();
  check('formatted date exposes only a match to a supplied goal fact',r.code===0&&dateCalls[0].state.page.controls.find(c=>c.name==='Travel date').goalMatches.includes('October 12, 2026'),r.out+r.err);
  check('unrelated field contents remain private',!JSON.stringify(dateCalls).includes('unrelated-hidden-value'));
  b('eval', `document.body.innerHTML='<div role="combobox" tabindex="0" aria-label="Change seating class"><span aria-hidden="true">Economy</span></div>'; 'ready'`);
  await mode('done');r=b('ai','task','Review the selected seating class');
  const seatingCalls=await(await fetch(base+'/calls')).json();
  check('visible combobox selection is retained alongside its accessible action label',r.code===0&&seatingCalls[0].state.page.controls.some(c=>c.name==='Change seating class'&&c.displayed==='Economy'),r.out+r.err);
  b('eval', `document.body.innerHTML='<div role="region" aria-label="Revenue chart"><svg width="300" height="150" aria-hidden="true"><rect x="50" y="40" width="30" height="100" fill="blue"/><text x="50" y="30">$710</text></svg></div>'; 'ready'`);
  await mode('done');r=b('ai','task','View the revenue chart');
  const graphCalls=await(await fetch(base+'/calls')).json();
  check('visible SVG chart labels reach the model even with accessibility duplication hidden',r.code===0&&graphCalls[0].state.page.graphics.some(g=>g.kind==='svg'&&g.label==='Revenue chart'&&g.labels.includes('$710')),r.out+r.err);
  r=b('close');check('close succeeds after task',r.code===0,r.err);
  const transcript=readFileSync(join(ENV.BROWSE_OUT,'transcript.md'),'utf8');check('task transcript retains goal without named value',transcript.includes(goal)&&!transcript.includes('buyer@example.invalid')&&!transcript.includes('fake-task-key'));
}finally{b('close');fixture.kill();rmSync(STORE,{recursive:true,force:true})}
console.log(`${checks-failed}/${checks} passed`);process.exitCode=failed?1:0;
