import {spawn,spawnSync} from 'node:child_process';
import {mkdtempSync,rmSync,symlinkSync,readFileSync,readdirSync,existsSync} from 'node:fs';
import {homedir,tmpdir} from 'node:os';
import {dirname,join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {parseTask} from '../scripts/ai-task.mjs';
const ROOT=dirname(dirname(fileURLToPath(import.meta.url)));
const STORE=mkdtempSync(join(tmpdir(),'browse-ai-task-'));
symlinkSync(join(homedir(),'.browse/camoufox-pw'),join(STORE,'camoufox-pw'));
const ENV={...process.env,BROWSE_HOME:STORE,BROWSE_OUT:join(STORE,'out'),BROWSE_PW_BASE:join(homedir(),'.browse/package.json'),BROWSE_SESSION:'task-test',BROWSE_ENGINE:process.env.BROWSE_ENGINE||'chromium',BROWSE_REMOTE:'',BROWSE_PROFILE:'',BROWSE_VIDEO:'0',BROWSE_HEADFUL:'0',BROWSE_CURSOR:'0',BROWSE_KEYLOG:'0',TYPESAFE_API_KEY:'fake-task-key',TYPESAFE_ENV_FILE:join(STORE,'absent')};
const b=(...args)=>{const r=spawnSync(process.execPath,[join(ROOT,'browse.mjs'),...args],{env:ENV,cwd:STORE,encoding:'utf8',timeout:30000});return{code:r.status,out:r.stdout||'',err:r.stderr||''}};
let checks=0,failed=0;
const check=(name,ok,detail='')=>{checks++;if(!ok)failed++;console.log(`${ok?'ok':'FAIL'} ${name}${ok?'':'\n'+detail}`)};
const fixture=spawn(process.execPath,[join(ROOT,'test/ai-task-fixture.mjs')],{stdio:['ignore','pipe','inherit']});
const port=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('fixture timeout')),10000);fixture.stdout.on('data',d=>{const m=/PORT (\d+)/.exec(String(d));if(m){clearTimeout(timer);resolve(+m[1])}})});
const base=`http://127.0.0.1:${port}`;ENV.TYPESAFE_API_URL=base+'/api';
const mode=m=>fetch(base+'/mode/'+m);
const goal='Open the catalog, open Desk lamp details, choose Express delivery, enter the supplied email, then submit the request.';
const task=(...args)=>b('ai','task',goal,'--value','email=buyer@example.invalid',...args);
try{
  const p=parseTask(['task','Search for "Typesafe" and open the result']);check('quoted goal supplies literal input',p.values[0].value==='Typesafe');
  for(const args of [['task'],['task','goal','--max-steps','0'],['task','goal','--task-timeout','0'],['task','goal','--value','bad'],['task','goal','--dry-run'],['task','goal','--until']]){const r=b('ai',...args);check(`invalid args fail before launching: ${args.join(' ')}`,r.code===1&&!existsSync(ENV.BROWSE_OUT),r.err)}
  let r=b('open',base);check('fixture opens',r.code===0,r.err);
  r=task();check('one command completes five-step workflow',r.code===0&&/completed; actions=5, queries=6/.test(r.out),r.out+r.err);
  check('actual final page confirms result',b('text','#confirmed').out.includes('Request confirmed'));
  check('submit runs exactly once',b('eval','document.documentElement.dataset.sends').out.trim()==='1');
  check('all five actions have screenshots',readdirSync(join(ENV.BROWSE_OUT,'shots')).filter(n=>n.includes('ai-task')).length===5);
  const calls=await(await fetch(base+'/calls')).json();
  check('each decision reads fresh controls after navigation',calls.length===6&&calls[0].state.page.text.includes('Store')&&calls.at(-1).state.page.text.includes('Request confirmed'));
  check('named fill value stays out of model requests',!JSON.stringify(calls).includes('buyer@example.invalid')&&!JSON.stringify(calls).includes('old@example.invalid'));
  check('history tracks actions and value references',calls[4].state.history.some(h=>h.action==='fill'&&h.value==='v0'));
  b('reload');await mode('ok');r=task('--until','#confirmed');check('deterministic completion avoids final model call',r.code===0&&/completed \(--until visible\); actions=5, queries=5/.test(r.out),r.out+r.err);
  b('reload');await mode('ok');r=task('--max-steps','1');check('step limit preserves completed action and stops',r.code===1&&/step limit reached/.test(r.err)&&b('eval','JSON.parse(document.documentElement.dataset.events)').out.includes('catalog')&&!b('eval','JSON.parse(document.documentElement.dataset.events)').out.includes('lamp'),r.err);
  check('partial steps are persisted before failure',readFileSync(join(ENV.BROWSE_OUT,'transcript.md'),'utf8').includes('ai task\n'));
  for(const m of ['blocked','low','invalid','false-done','error']){b('reload');await mode(m);r=task();check(`${m} stops without clicking`,r.code===1&&b('eval','JSON.parse(document.documentElement.dataset.events).length').out.trim()==='0',r.out+r.err)}
  b('open','data:text/html,<h1>Complete</h1><input value=private-data-url-value>');await mode('done');r=task();
  const dataCalls=await(await fetch(base+'/calls')).json();check('data URL source and input values stay out of requests',r.code===0&&!JSON.stringify(dataCalls).includes('private-data-url-value')&&dataCalls[0].state.page.url==='data:',r.err);
  b('open',base);await mode('done');r=task('--until','#confirmed');check('model cannot bypass completion selector',r.code===1&&/selector is not visible/.test(r.err),r.err);
  b('reload');b('eval',"document.querySelector('#catalog').onclick=()=>{};'ready'");await mode('loop');r=task();check('no-op cycle stops before repeating click',r.code===1&&/stalled/.test(r.err)&&/actions=1/.test(r.err),r.err);
  b('reload');await mode('wait');r=task();check('wait loop is bounded',r.code===1&&/stalled/.test(r.err)&&/actions=3/.test(r.err),r.err);
  b('reload');await mode('slow');r=task('--task-timeout','150');check('total deadline cancels inference',r.code===1&&/cancelled|budget/.test(r.err)&&b('eval','JSON.parse(document.documentElement.dataset.events).length').out.trim()==='0',r.err);
  b('reload');await mode('slow');
  const run=JSON.parse(readFileSync(join(STORE,'run/task-test.json'),'utf8'));
  const endpoint=`http://127.0.0.1:${run.port}`;
  const controller=new AbortController();
  const active=fetch(endpoint,{method:'POST',signal:controller.signal,body:JSON.stringify({cmd:'ai',args:['task',goal,'--value','email=buyer@example.invalid'],ai:{key:'fake-task-key',endpoint:base+'/api'}})}).catch(()=>null);
  await new Promise(r=>setTimeout(r,200));
  const concurrent=await(await fetch(endpoint,{method:'POST',body:JSON.stringify({cmd:'click',args:['#catalog']})})).json();
  check('concurrent browser command is rejected during task',!concurrent.ok&&/task is running/.test(concurrent.error));
  controller.abort();await active;await new Promise(r=>setTimeout(r,100));
  r=b('eval','JSON.parse(document.documentElement.dataset.events).length');check('disconnected caller cancels task and unlocks session',r.code===0&&r.out.trim()==='0',r.out+r.err);
  await mode('ok');b('reload');
  const waiting=fetch(endpoint,{method:'POST',body:JSON.stringify({cmd:'wait',args:['400']})});
  await new Promise(r=>setTimeout(r,40));
  const occupied=await(await fetch(endpoint,{method:'POST',body:JSON.stringify({cmd:'ai',args:['task',goal],ai:{key:'fake-task-key',endpoint:base+'/api'}})})).json();
  check('task cannot overlap an earlier browser command',!occupied.ok&&/another browser command/.test(occupied.error));await waiting;
  b('click','#catalog');b('click','#lamp');await mode('slow');
  b('eval',"setTimeout(()=>document.querySelector('#delivery').options[1].label='Unexpected option',500);'scheduled'");
  r=task();check('changed native option is rejected before selection',r.code===1&&/target changed/.test(r.err),r.err);
  b('reload');b('click','#catalog');b('click','#lamp');b('selectOption','#delivery','Express');await mode('bad-value');
  r=task();check('uncertain supplied value prevents filling',r.code===1&&/no confident supplied/.test(r.err)&&b('eval',"document.querySelector('#email').value").out.trim()==='old@example.invalid',r.err);
  await mode('ok');b('reload');r=task();check('session remains usable after cancellation',r.code===0,r.out+r.err);
  r=b('close');check('close succeeds after task',r.code===0,r.err);
  const transcript=readFileSync(join(ENV.BROWSE_OUT,'transcript.md'),'utf8');check('task transcript retains goal without named value',transcript.includes(goal)&&!transcript.includes('buyer@example.invalid')&&!transcript.includes('fake-task-key'));
}finally{b('close');fixture.kill();rmSync(STORE,{recursive:true,force:true})}
console.log(`${checks-failed}/${checks} passed`);process.exitCode=failed?1:0;
